/**
 * Lego slot wiring + config — GENERATED by _legos_config_generator.py
 * at substrate install time. DO NOT hand-edit.
 *
 * Spec authority: NEXUS_PORTFOLIO_RUNTIME_SPEC.md §4.4.
 */

export interface LegoSlot {
  readonly name: string;
  readonly contract: string;
  readonly description?: string;
}

export interface LegoConfig {
  readonly name: string;
  readonly version: string;
  readonly isStub: boolean;
  readonly slots: readonly LegoSlot[];
  readonly config: Record<string, unknown>;
}

export const LEGOS: readonly LegoConfig[] = [
  {
    "config": {
      "properties": {
        "default_permissions": {
          "description": "Roles that have access to the admin console by default.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enable_feature_flags": {
          "default": true,
          "description": "Enable the feature flags admin section.",
          "type": "boolean"
        },
        "enable_impersonation": {
          "default": false,
          "description": "Show impersonation button in admin shell. Actual session-switching is deferred to a future security-review sprint.\n",
          "type": "boolean"
        }
      },
      "required": [
        "default_permissions",
        "enable_impersonation",
        "enable_feature_flags"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "admin-console",
    "slots": [
      {
        "contract": "react-component",
        "description": "Extra navigation items injected into the admin sidebar by other legos.",
        "name": "admin_nav_extra"
      },
      {
        "contract": "react-component",
        "description": "Widgets contributed to the admin dashboard overview page.",
        "name": "admin_dashboard_widgets"
      },
      {
        "contract": "react-component",
        "description": "Per-row action buttons injected into the admin users table (e.g. Identity & Access \"force delete\" / \"revoke sessions\").",
        "name": "admin_user_actions"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "properties": {
        "events": {
          "properties": {
            "taxonomy": {
              "default": [
                "page_view",
                "sign_up",
                "activation",
                "purchase"
              ],
              "description": "Canonical event names the product emits.",
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "funnels": {
          "default": [],
          "description": "Named funnels as ordered event-name lists.",
          "items": {
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "events"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "analytics-and-telemetry",
    "slots": [
      {
        "contract": "react-component",
        "description": "Metrics dashboard widget (funnels + key counts).",
        "name": "analytics_dashboard"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "tier_ladder": [
        {
          "name": "Starter",
          "price_id": "price_1TgHUp6WMeYkDDIuZmrQrq5Y",
          "amount": 14900,
          "interval": "month"
        },
        {
          "name": "Professional",
          "price_id": "price_1TgHUp6WMeYkDDIuiD5HCosa",
          "amount": 39900,
          "interval": "month"
        },
        {
          "name": "Enterprise",
          "price_id": "price_1TgHUp6WMeYkDDIu7qngCXji",
          "amount": 99900,
          "interval": "month"
        }
      ],
      "default_currency": "usd",
      "enable_proration": true,
      "trial_days": 0
    },
    "isStub": false,
    "name": "billing-and-subscriptions",
    "slots": [
      {
        "contract": "react-component",
        "description": "Extra form fields injected into the checkout flow (e.g., promo code, referral source).",
        "name": "checkout_extra_fields"
      },
      {
        "contract": "server-hook",
        "description": "Server-side hook to redirect after successful subscription creation.",
        "name": "post_subscription_redirect"
      },
      {
        "contract": "react-component",
        "description": "Per-subscription metadata fields appended to the Stripe subscription record.",
        "name": "subscription_extra_metadata"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "outreach": {
          "properties": {
            "daily_send_cap": {
              "default": 50,
              "description": "Max agent-initiated outreach sends per day (0 = unlimited).",
              "minimum": 0,
              "type": "integer"
            },
            "require_approval": {
              "default": true,
              "description": "Whether agent-drafted outreach must be approved before sending.",
              "type": "boolean"
            }
          },
          "type": "object"
        },
        "pipeline": {
          "properties": {
            "auto_advance": {
              "default": false,
              "description": "Whether the agent may advance a contact's stage without approval.",
              "type": "boolean"
            },
            "stages": {
              "default": [
                "new",
                "contacted",
                "qualified",
                "proposal",
                "won",
                "lost"
              ],
              "description": "Ordered pipeline stage names.",
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "scoring": {
          "properties": {
            "hot_lead_threshold": {
              "default": 70,
              "description": "score_lead value (0-100) above which a lead is flagged hot.",
              "maximum": 100,
              "minimum": 0,
              "type": "number"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "pipeline",
        "outreach"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "crm-and-lifecycle",
    "slots": [
      {
        "contract": "react-component",
        "description": "Embeddable lead-capture form (name/email/source) for marketing pages. Posts to the lego's lead-capture API; the agent triages + scores on arrival.\n",
        "name": "lead_capture_form"
      },
      {
        "contract": "react-component",
        "description": "Contact detail sidebar (history + AI-proposed next action) shown on a contact record. Renders the agent's propose_next_action recommendation.\n",
        "name": "contact_sidebar"
      },
      {
        "contract": "server-hook",
        "description": "Server hook fired when a new lead is captured \u2014 triggers agent scoring + (optionally) an outreach draft. No-op when unconfigured.\n",
        "name": "after_lead_captured_hook"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "rate_limit": {
          "properties": {
            "default_rpm": {
              "default": 600,
              "type": "integer"
            },
            "enforce": {
              "default": true,
              "type": "boolean"
            }
          },
          "type": "object"
        },
        "webhooks": {
          "properties": {
            "events": {
              "default": [
                "user.created",
                "payment.succeeded"
              ],
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "rate_limit"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "developer-surface",
    "slots": [
      {
        "contract": "react-component",
        "description": "API key management (create/rotate/revoke) for developers.",
        "name": "api_keys_panel"
      },
      {
        "contract": "react-component",
        "description": "Webhook endpoint management + delivery status.",
        "name": "webhooks_panel"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "storage": {
          "properties": {
            "allowed_types": {
              "default": [
                "image/png",
                "image/jpeg",
                "application/pdf",
                "text/csv"
              ],
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "max_file_mb": {
              "default": 25,
              "type": "integer"
            }
          },
          "type": "object"
        },
        "virus_scan": {
          "properties": {
            "required": {
              "default": true,
              "type": "boolean"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "storage"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "files-and-media",
    "slots": [
      {
        "contract": "react-component",
        "description": "Drag-and-drop file upload widget with progress + scan status.",
        "name": "file_uploader"
      },
      {
        "contract": "react-component",
        "description": "User's file list with category + download.",
        "name": "file_list"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "mfa": {
          "description": "MFA configuration (wired in 2.2)",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "enforcement": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "password_policy": {
          "description": "Password strength requirements",
          "properties": {
            "min_length": {
              "type": "integer"
            },
            "require_digit": {
              "type": "boolean"
            },
            "require_special": {
              "type": "boolean"
            },
            "require_uppercase": {
              "type": "boolean"
            }
          },
          "type": "object"
        },
        "providers": {
          "description": "Authentication providers to enable",
          "items": {
            "enum": [
              "email",
              "google_oauth",
              "github_oauth",
              "passkey",
              "totp"
            ],
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "providers",
        "password_policy"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "identity-and-access",
    "slots": [
      {
        "contract": "react-component",
        "description": "Inject custom fields or UI elements above the standard email/password inputs on the signup form.\n",
        "name": "before_signup_fields"
      },
      {
        "contract": "react-component",
        "description": "Legal acknowledgment block shown at the bottom of the signup form. Defaults to a standard ToS + privacy placeholder; full email-linked template lands in 2.2.\n",
        "name": "signup_legal_acknowledgment"
      },
      {
        "contract": "server-hook",
        "description": "Server hook executed after a successful login to determine where to redirect the user. Falls back to /dashboard when not configured.\n",
        "name": "after_login_redirect"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "cookie_banner_enabled": {
          "default": true,
          "description": "Show cookie consent banner to new visitors.",
          "type": "boolean"
        },
        "jurisdiction": {
          "default": "us",
          "description": "Primary legal jurisdiction for this company's documents.",
          "enum": [
            "us",
            "eu",
            "uk",
            "ca",
            "au",
            "global"
          ],
          "type": "string"
        },
        "liability_boundary_class": {
          "default": "assistant",
          "description": "Mirrors spec \u00a78. Controls strictness of disclosure flows. regulated_advisor and fiduciary companies get additional disclosure requirements wired into every external communication.\n",
          "enum": [
            "tool",
            "assistant",
            "fiduciary",
            "regulated_advisor"
          ],
          "type": "string"
        }
      },
      "required": [
        "jurisdiction",
        "cookie_banner_enabled",
        "liability_boundary_class"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "legal-and-compliance",
    "slots": [
      {
        "contract": "react-component",
        "description": "Additional links injected into the site footer alongside the standard Terms / Privacy / Cookie Policy links. Other legos may inject their own compliance links here (e.g. sub-processor list, DPA download).\n",
        "name": "extra_legal_links"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Terms of Service document. Use for company-specific clauses that cannot go in the base template.\n",
        "name": "policy_addendum_terms_of_service"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Privacy Policy document.\n",
        "name": "policy_addendum_privacy_policy"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Cookie Policy document.\n",
        "name": "policy_addendum_cookie_policy"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Accessibility Statement document.\n",
        "name": "policy_addendum_accessibility_statement"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "properties": {
        "contradiction_threshold": {
          "default": 3,
          "description": "Contradicting newer observations before a long-term memory is demoted.",
          "maximum": 10,
          "minimum": 1,
          "type": "integer"
        },
        "knowledge_compiler_debounce_seconds": {
          "default": 300,
          "description": "Min seconds between compiler runs per company.",
          "maximum": 3600,
          "minimum": 30,
          "type": "integer"
        },
        "long_term_eviction_no_retrieval_days": {
          "default": 90,
          "description": "Long-term entries flagged low-value if not retrieved in N days.",
          "maximum": 365,
          "minimum": 30,
          "type": "integer"
        },
        "working_memory_ttl_days": {
          "default": 7,
          "description": "Working-tier memories evicted after N idle days (spec \u00a75.6).",
          "maximum": 90,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "working_memory_ttl_days",
        "long_term_eviction_no_retrieval_days"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "memory-and-knowledge",
    "slots": [
      {
        "contract": "react-component",
        "description": "Admin-console pane showing per-company memory rows + tier badges",
        "name": "admin_memory_inspector"
      },
      {
        "contract": "react-component",
        "description": "User-facing GDPR export + forget-me controls",
        "name": "user_memory_export"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "properties": {
        "default_channels": {
          "default": [
            "email",
            "in_app"
          ],
          "description": "Channels enabled by default for new users. User can opt out per-channel via /api/notifications/preferences.",
          "items": {
            "enum": [
              "email",
              "in_app",
              "web_push",
              "sms"
            ],
            "type": "string"
          },
          "type": "array"
        },
        "rate_limit_per_user_per_hour": {
          "default": 30,
          "maximum": 1000,
          "minimum": 1,
          "type": "integer"
        },
        "resend_from_email": {
          "description": "Verified sender address for Resend (e.g. notifications@example.com).",
          "type": "string"
        },
        "twilio_messaging_service_sid": {
          "description": "Optional Twilio Messaging Service SID. Required only if 'sms' is in default_channels.",
          "type": "string"
        },
        "web_push_vapid_public_key": {
          "description": "Optional VAPID public key for web push. Required only if 'web_push' in default_channels.",
          "type": "string"
        }
      },
      "required": [
        "resend_from_email",
        "default_channels"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "notifications",
    "slots": [
      {
        "contract": "react-component",
        "description": "HTML injected at the top of every transactional email (logo, brand banner).",
        "name": "email_layout_header"
      },
      {
        "contract": "react-component",
        "description": "HTML injected at the bottom of every transactional email (legal footer, unsubscribe link).",
        "name": "email_layout_footer"
      },
      {
        "contract": "react-component",
        "description": "Per-row action buttons injected into the in-app inbox.",
        "name": "in_app_inbox_extra_actions"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "properties": {
        "sample_data": {
          "properties": {
            "enabled": {
              "default": true,
              "type": "boolean"
            }
          },
          "type": "object"
        },
        "steps": {
          "default": [
            "verify_email",
            "complete_profile",
            "first_action",
            "invite_team"
          ],
          "description": "Ordered onboarding step keys.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "steps"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "onboarding",
    "slots": [
      {
        "contract": "react-component",
        "description": "First-run checklist widget shown until onboarding completes.",
        "name": "onboarding_checklist"
      },
      {
        "contract": "react-component",
        "description": "Product tour overlay for the first session.",
        "name": "welcome_tour"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "invitations": {
          "properties": {
            "expiry_days": {
              "default": 14,
              "minimum": 1,
              "type": "integer"
            }
          },
          "type": "object"
        },
        "roles": {
          "default": [
            "owner",
            "admin",
            "member",
            "viewer"
          ],
          "description": "RBAC roles, most-privileged first.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "seats": {
          "properties": {
            "default_limit": {
              "default": 5,
              "description": "Default seat limit for a new org (0 = unlimited).",
              "minimum": 0,
              "type": "integer"
            },
            "enforce": {
              "default": true,
              "description": "Whether to block invitations beyond the seat limit.",
              "type": "boolean"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "roles",
        "seats"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "organizations-and-teams",
    "slots": [
      {
        "contract": "react-component",
        "description": "Org switcher dropdown for the app shell (when a user belongs to >1 org).\n",
        "name": "org_switcher"
      },
      {
        "contract": "react-component",
        "description": "Members management table (role, seat, invite/remove) for org admins.\n",
        "name": "members_table"
      },
      {
        "contract": "server-hook",
        "description": "Server hook fired when a member accepts an invitation \u2014 used for onboarding + seat accounting. No-op when unconfigured.\n",
        "name": "after_member_joined_hook"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "export": {
          "properties": {
            "enabled": {
              "default": true,
              "type": "boolean"
            },
            "format": {
              "default": "json",
              "enum": [
                "json",
                "csv"
              ],
              "type": "string"
            },
            "retention_days": {
              "default": 7,
              "description": "How long a generated export download link stays valid.",
              "minimum": 1,
              "type": "integer"
            }
          },
          "type": "object"
        },
        "profile": {
          "properties": {
            "required_fields": {
              "default": [
                "display_name",
                "avatar_url",
                "timezone"
              ],
              "description": "Profile fields that count toward the completion score.",
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "stale_account": {
          "properties": {
            "inactive_days_threshold": {
              "default": 90,
              "description": "Days of inactivity before detect_stale_account flags an account.",
              "minimum": 1,
              "type": "integer"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "export"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "profile-and-account",
    "slots": [
      {
        "contract": "react-component",
        "description": "The profile editor panel (display name, avatar, bio, timezone, preferences). Mounted in the account settings surface.\n",
        "name": "profile_settings_panel"
      },
      {
        "contract": "react-component",
        "description": "List of connected OAuth/identity providers with connect/disconnect.\n",
        "name": "connected_accounts_panel"
      },
      {
        "contract": "react-component",
        "description": "GDPR \"download my data\" button that requests an account export.\n",
        "name": "account_export_button"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "facets": {
          "default": [
            "entity_type",
            "category"
          ],
          "description": "Facet fields exposed in the results panel.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "index": {
          "properties": {
            "entity_types": {
              "default": [
                "page",
                "document",
                "contact",
                "ticket"
              ],
              "description": "Entity types indexed for search.",
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "index"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "search",
    "slots": [
      {
        "contract": "react-component",
        "description": "Global cmd+K search palette mounted in the app shell.",
        "name": "command_palette"
      },
      {
        "contract": "react-component",
        "description": "Faceted results panel with sort + pagination.",
        "name": "search_results_panel"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "moderation": {
          "properties": {
            "auto_hide_spam": {
              "default": false,
              "type": "boolean"
            },
            "require_approval": {
              "default": true,
              "type": "boolean"
            }
          },
          "type": "object"
        },
        "referrals": {
          "properties": {
            "enabled": {
              "default": true,
              "type": "boolean"
            },
            "reward_type": {
              "default": "credit",
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "moderation"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "social-and-engagement",
    "slots": [
      {
        "contract": "react-component",
        "description": "Comment thread component for any entity (post/product/etc).",
        "name": "comment_thread"
      },
      {
        "contract": "react-component",
        "description": "Reaction (like/etc) bar for an entity.",
        "name": "reaction_bar"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "deflection": {
          "description": "AI-deflection behavior \u2014 the agent attempts a KB-grounded answer before opening a ticket.",
          "properties": {
            "enabled": {
              "default": true,
              "type": "boolean"
            },
            "min_kb_confidence": {
              "default": 0.7,
              "description": "Minimum suggest_kb_article relevance (0-1) before auto-deflecting instead of opening a ticket.",
              "maximum": 1.0,
              "minimum": 0.0,
              "type": "number"
            }
          },
          "type": "object"
        },
        "escalation": {
          "description": "When the agent must hand a ticket to a human.",
          "properties": {
            "auto_escalate_priorities": {
              "default": [
                "high",
                "urgent"
              ],
              "description": "Ticket priorities the agent never auto-resolves (always escalates to a human queue).",
              "items": {
                "enum": [
                  "low",
                  "normal",
                  "high",
                  "urgent"
                ],
                "type": "string"
              },
              "type": "array"
            },
            "escalation_channel": {
              "description": "Where escalations land (e.g. a Slack channel or email alias). Substrate-resolved.",
              "type": "string"
            }
          },
          "type": "object"
        },
        "kb": {
          "properties": {
            "public": {
              "default": true,
              "description": "Whether the KB index is publicly browsable (vs auth-gated).",
              "type": "boolean"
            }
          },
          "type": "object"
        }
      },
      "required": [
        "deflection",
        "escalation"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "support-and-help",
    "slots": [
      {
        "contract": "react-component",
        "description": "Floating launcher button injected into the substrate's app shell. Opens the in-app SupportWidget (KB search + new-ticket form + ticket history).\n",
        "name": "support_widget_launcher"
      },
      {
        "contract": "react-component",
        "description": "Nav/footer link to the company's help center / KB index. Renders nothing when the company has no published KB articles.\n",
        "name": "help_center_link"
      },
      {
        "contract": "server-hook",
        "description": "Server hook executed when a ticket transitions to resolved \u2014 used to trigger a CSAT feedback request via the notifications lego. No-op when unconfigured.\n",
        "name": "after_ticket_resolved_hook"
      }
    ],
    "version": "1.0.0"
  }
];

export function findSlotProvider(slotName: string): LegoConfig | undefined {
  return LEGOS.find((lego) =>
    lego.slots.some((slot) => slot.name === slotName),
  );
}
