/**
 * Blog post page (gtm-marketing-launch-001).
 *
 * Renders one published post. content_html is produced by the Nexus
 * marketing engine (markdown → sanitized HTML at publish time) and stored
 * in the company's own DB — same trust model as the legal surface's
 * content_html (rendered with dangerouslySetInnerHTML).
 */
import type { JSX } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPostBySlug } from "@/lib/blog";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// Open-Graph / Twitter share metadata. Prefers the branded OG share card
// (blog_posts.og_image_url, generated by the Nexus marketing visual team);
// falls back to the editorial hero. Without an image the card still carries
// title + description.
export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const post = await getPostBySlug(params.slug);
  if (!post) return { title: "Post not found" };
  const image = post.og_image_url || post.hero_image_url || undefined;
  const description = post.description || undefined;
  return {
    title: post.title,
    description,
    openGraph: {
      type: "article",
      title: post.title,
      description,
      images: image ? [{ url: image }] : undefined,
    },
    twitter: {
      card: image ? "summary_large_image" : "summary",
      title: post.title,
      description,
      images: image ? [image] : undefined,
    },
  };
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}

export default async function BlogPostPage({
  params,
}: {
  params: { slug: string };
}): Promise<JSX.Element> {
  const post = await getPostBySlug(params.slug);
  if (!post) notFound();
  return (
    <main>
      <p>
        <Link href="/blog">← All posts</Link>
      </p>
      <article>
        {post.hero_image_url ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={post.hero_image_url}
            alt={post.title}
            style={{ width: "100%", borderRadius: 10, marginBottom: 20, aspectRatio: "16 / 9", objectFit: "cover" }}
          />
        ) : null}
        <h1>{post.title}</h1>
        <p>
          <small>
            {formatDate(post.published_at)} · {post.author}
          </small>
        </p>
        {post.audio_url ? (
          <figure style={{ margin: "0 0 20px" }}>
            <figcaption style={{ fontSize: 13, opacity: 0.7, marginBottom: 6 }}>
              Listen to this post
            </figcaption>
            <audio controls preload="none" src={post.audio_url} style={{ width: "100%" }}>
              Your browser does not support the audio element.
            </audio>
          </figure>
        ) : null}
        <div dangerouslySetInnerHTML={{ __html: post.content_html }} />
      </article>
    </main>
  );
}
